### ISSUE TITLE
Update settings and config.ini template for PROJECT_APP

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/marco-portal2#1]
config.ini template needs:

* [x] PROJECT_APP = False
?? * [ ] PROJECT_SETTINGS_FILE = False

settings.py:

* [x] (cfg get 'PROJECT_APP' - if  so, add to INSTALLED_APPS)
* [x] (cfg get 'PROJECT_SETTINGS_FILE' - if exists, from PROJECT_APP.settings import *

**Comment by pollardld** [comment]
Added in commit 6fc76ceb65b8664e6c9978db27bd60704172864a
